Repository nicolascarrica/marketplace_rust, pull requests merged in 2025-07, with the labels that each got.

#1 chore: restructura de archivos
  .github/PULL_REQUEST_TEMPLATE.md
  lib.rs
  types/enums.rs
  types/mod.rs
  types/orden.rs
  types/producto.rs
  types/publicacion.rs
  types/usuario.rs
Labels: ready for merge

#4 Feat/publicaciones-basic-structure
  Cargo.toml
  types/enums.rs
  types/publicacion.rs
Labels: ready for merge

#8 Nicolas rework
  Cargo.lock
  lib.rs
  types/calificacion.rs
  types/enums.rs
  types/errores.rs
  types/mod.rs
  types/orden.rs
  types/producto.rs
  types/usuario.rs
Labels: ready for review

#11 revamp libs.rs
  lib.rs
Labels: ready for review

#14 Actualizar libs file
  lib.rs
Labels: ready for review

#22 Primer entregable basico
  lib.rs
  types/calificacion.rs
  types/mod.rs
  types/orden.rs
  types/usuario.rs
Labels: ready for review

#23 Publicaciones y registro productos
  lib.rs
  types/enums.rs
  types/errores.rs
  types/mod.rs
  types/orden.rs
  types/producto.rs
  types/publicacion.rs
  types/usuario.rs
Labels: ready for review

#24 feat: Actualizar Rol method
  lib.rs
Labels: ready for merge, ready for review

#28 Crear publicacion y refactor
  lib.rs
  tarpaulin-report.html
Labels: ready for review

#32 feat: Delete new orden duplicate code and comments
  .gitignore
  lib.rs
Labels: ready for review

#34 chore: Actualizar readme
  readme.md
Labels: ready for merge
